package:
  name: cargo
  version: "0.23.0"

source:
  git_url: https://github.com/rust-lang/cargo
  git_tag: 0.23.0

build:
  number: 3

requirements:
  build:
    - system [linux]
    - openssl [linux]
    - curl
    - libgit2
    - libssh2
    - rustc
    - cmake
  run:
    - system [linux]
    - openssl [linux]
    - curl
    - libgit2
    - libssh2

about:
  home: http://crates.io/
  license: MIT/Apache
  summary: The Rust package manager
