package:
  name: binutils-or1k-linux
  version: 2.30

source:
  fn: binutils-2.30.tar.bz2
  url: https://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.bz2
  sha256: efeade848067e9a03f1918b1da0d37aaffa0b0127a06b5e9236229851d9d0c09
  patches:
    - hack-libiconv.patch

build:
  number: 7

requirements:
  build:
    - system # [not win]
    - libiconv
  run:
    - libiconv

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL
  summary: 'A set of programming tools for creating and managing binary programs, object files, libraries, profile data, and assembly source code.'
