# /!\ ACHTUNG /!\
# The build number 1 on anaconda.org is a manually hacked up version
# that I did to save time. It was not freshly built from this recipe.

package:
  name: binutils-or1k-linux
  version: 2.27

source:
  fn: binutils-2.27.tar.bz2
  url: https://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2
  sha256: 369737ce51587f92466041a97ab7d2358c6d9e1b6490b3940eb09fb0a9a6ac88
  patches:
    - fix-R_OR1K_GOTOFF-relocations.patch

build:
  number: 5

requirements:
  build:
    - system # [not win]

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL
  summary: 'A set of programming tools for creating and managing binary programs, object files, libraries, profile data, and assembly source code.'
