package:
  name: rustc
  version: "1.18.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.18.0

build:
  number: 13

requirements:
  build:
    - system [linux]
    - cmake
    - llvm-or1k 3.9.1 19
    - curl
  run:
    - system [linux]
    - llvm-or1k

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
