package:
  name: rustc
  version: "1.25.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.25.0

build:
  number: 20
  detect_binary_files_with_prefix: false

requirements:
  build:
    - system [linux]
    - cmake
    - llvm-or1k 6.0.0
    - curl
  run:
    - system [linux]
    - llvm-or1k 6.0.0
    - libcurl

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
