package:
  name: rustc
  version: "1.22.1"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.22.1

build:
  number: 17
  detect_binary_files_with_prefix: false

requirements:
  build:
    - system [linux]
    - cmake
    - llvm-or1k 4.0.1 23
    - curl
  run:
    - system [linux]
    - llvm-or1k

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
