package:
  name: pythonparser
  version: 1.0

source:
  git_url: https://github.com/m-labs/pythonparser
  git_tag: 1.0

build:
  number: 8
  string: py_8
  noarch: python
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - regex
  run:
    - regex

test:
  imports:
    - pythonparser

about:
  home: http://m-labs.hk/pythonparser/
  license: BSD
  summary: 'PythonParser is a Python parser written specifically for use in tooling. It parses source code into an AST that is a superset of Python’s built-in ast module, but returns precise location information for every token.'
