package:
  name: quamash
  version: 0.5.5

source:
  fn: version-0.5.5.tar.gz
  url: https://github.com/harvimt/quamash/archive/version-0.5.5.tar.gz#md5=4aeb8c04521f2eb8cd7a3e3edd309007
  md5: 4aeb8c04521f2eb8cd7a3e3edd309007

build:
  number: 2
  noarch_python: true
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - pyqt5
  run:
    - python
    - pyqt5

test:
  imports:
    - quamash

about:
  home: https://github.com/harvimt/quamash
  license: BSD
  summary: 'Implementation of the PEP 3156 Event-Loop with Qt'
