package:
  name: openocd
  version: "0.10.0"

source:
  git_rev: 8cea56c63e14162ea3e78004b16c5e3049f9e743
  git_url: https://github.com/m-labs/openocd

build:
  number: 5

requirements:
  build:
    - system # [linux]
    - libusb >=1.0.16
  run:
    - libusb >=1.0.16
    - bscan-spi-bitstreams 0.10.0 2

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
