package:
  name: openocd
  version: 0.10.0+git

source:
  git_rev: 977d9e41ac6942c7754a6c1bad2d6e5b8b6b9b3f
  git_url: https://github.com/m-labs/openocd

build:
  number: 1

requirements:
  build:
    - system # [linux]
    - libusb >=1.0.16
    - libtool ==2.4.6
  run:
    - libusb >=1.0.16

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
