package:
  name: openocd
  version: "0.10.0"

source:
  git_rev: 0b26b289fb043c9814631e651f9d173db0861c59
  git_url: https://github.com/m-labs/openocd

build:
  string: 7

requirements:
  build:
    - system # [linux]
    - libusb >=1.0.16
  run:
    - libusb >=1.0.16
    - bscan-spi-bitstreams 0.10.0 2

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
