package:
  name: rust-core-or1k
  version: "1.23.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.23.0

build:
  number: 19

requirements:
  build:
    - rustc 1.23.0 17
  run:
    - rustc 1.23.0 17

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
