package:
  name: rust-core-or1k
  version: "1.22.1"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.22.1

build:
  number: 18

requirements:
  build:
    - rustc 1.22.1 17
  run:
    - rustc 1.22.1 17

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
