package:
  name: rust-core-or1k
  version: "1.18.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.18.0

build:
  number: 14

requirements:
  build:
    - rustc 1.18.0 14
  run:
    - rustc 1.18.0 14

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
