package:
  name: rust-core-or1k
  version: "1.20.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.20.0

build:
  number: 16

requirements:
  build:
    - rustc 1.20.0 15
  run:
    - rustc 1.20.0 15

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
