package:
  name: rust-core-or1k
  version: "1.28.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.28.0

build:
  number: 21

requirements:
  build:
    - rustc 1.28.0 21
  run:
    - rustc 1.28.0 21

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
