package:
  name: rust-core-or1k
  version: "1.25.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.25.0

build:
  number: 20

requirements:
  build:
    - rustc 1.25.0 20
  run:
    - rustc 1.25.0 20

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
