package:
  name: sphinxcontrib-wavedrom
  version: "1.3.1"

source:
  fn: sphinxcontrib-wavedrom-1.3.1.tar.gz
  url: https://files.pythonhosted.org/packages/52/61/716daebc1b212b11e810b991bf5cf5b052b9fe0699981ab974ccb33fb60b/sphinxcontrib-wavedrom-1.3.1.tar.gz
  sha256: db2c15854d361521f5a518234fcdf4fd2cdaa27c9673612923e37c0b869950e0

build:
  noarch_python: True
  # preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - sphinx >=0.6

  run:
    - python
    - sphinx >=0.6

test:
  imports:
    - sphinxcontrib.wavedrom

about:
  home: https://github.com/bavovanachte/sphinx-wavedrom
  license: MIT license
  summary: 'A sphinx extension that allows generating wavedrom diagrams based on their textual representation'
