#!/bin/bash

mkdir build
cd build
if [ $(uname -m) = "i686" ]; then
  COMPILER32=-DCMAKE_C_COMPILER="cc -m32" -DCMAKE_CXX_COMPILER="c++ -m32"
fi
cmake .. $COMPILER32 -DCMAKE_INSTALL_PREFIX=$PREFIX -DOPENSSL_ROOT_DIR=$PREFIX -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_PREFIX_PATH=$PREFIX
make -j2
make install
