package:
  name: jesd204b
  version: 0.3

source:
  git_url: https://github.com/m-labs/jesd204b
  git_tag: master

build:
  number: 1
  string: py_1
  noarch_python: true
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - migen
    - misoc
  run:
    - migen
    - misoc

test:
  imports:
    - jesd204b

about:
  home: https://github.com/m-labs/jesd204b
  license: LGPLv3+
  summary: 'A small footprint and configurable JESD204B core'
