#!/bin/bash -ex

mkdir build
cd build
cmake .. $COMPILER32 \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DLLVM_BUILD_LLVM_DYLIB=ON \
  -DLLVM_LINK_LLVM_DYLIB=ON \
  -DLLVM_TARGETS_TO_BUILD=X86\;ARM \
  -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=OR1K \
  -DLLVM_ENABLE_ASSERTIONS=OFF \
  -DLLVM_INSTALL_UTILS=ON \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_DOCS=OFF \
  -DLLVM_INCLUDE_EXAMPLES=OFF
make -j2
make install
