package:
  name: llvm-or1k
  version: "3.9.1"

source:
  git_url: https://github.com/m-labs/llvm-or1k
  git_tag: artiq-3.9

build:
  number: 22

requirements:
  build:
    - system [linux]
  run:
    - system [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.9.1/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
