package:
  name: llvm-or1k
  version: "6.0.0"

source:
  git_url: https://github.com/m-labs/llvm-or1k
  git_tag: artiq-6.0

build:
  number: 25

requirements:
  build:
    - system [linux]
  run:
    - system [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/6.0.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
