package:
  name: microscope
  version: 1.3

source:
  git_url: https://github.com/m-labs/microscope
  git_tag: 1.3

build:
  noarch: python
  number: 1
  string: py_1
  entry_points:
    - microscope = microscope.microscope:main
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5.0
    - migen
    - pyserial
    - msgpack-python
    - prettytable
  run:
    - python >=3.5.0
    - migen
    - pyserial
    - msgpack-python
    - prettytable

test:
  imports:
    - microscope

about:
  home: https://m-labs.hk
  license: 2-clause BSD
  summary: 'A simple FPGA logic analyzer for Migen designs'
