package:
  name: microscope
  version: 1.0

source:
  git_url: https://github.com/m-labs/microscope
  git_tag: 1.0

{% set data = load_setup_py_data() %}

build:
  noarch: python
  number: 1
  string: py_1
  entry_points:
    # NOTE: conda-build cannot distinguish between console and gui scripts
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5.0
    - migen
    - pyserial
    - msgpack-python
    - prettytable
  run:
    - python >=3.5.0
    - migen
    - pyserial
    - msgpack-python
    - prettytable

test:
  imports:
    - microscope

about:
  home: https://m-labs.hk
  license: 2-clause BSD
  summary: 'A simple FPGA logic analyzer for Migen designs'
