package:
    name: llvmlite-artiq
    version: "0.20.0"

build:
    number: 1

source:
    git_url: https://github.com/m-labs/llvmlite
    git_tag: artiq-4.0

requirements:
    build:
        - python
        - llvm-or1k 4.0.1
        - setuptools
    run:
        - python

test:
    imports:
        - llvmlite_artiq
        - llvmlite_artiq.binding

about:
    home: https://pypi.python.org/pypi/llvmlite/
    license: BSD
