package:
    name: llvmlite-artiq
    version: 0.12.0

build:
    number: 0

source:
    git_url: https://github.com/m-labs/llvmlite
    git_tag: artiq-3.9

requirements:
    build:
        - python
        - llvm-or1k 3.9.*
        - setuptools
    run:
        - python

test:
    imports:
        - llvmlite_artiq
        - llvmlite_artiq.binding

about:
    home: https://pypi.python.org/pypi/llvmlite/
    license: BSD
