package:
    name: llvmlite-artiq
    version: "0.23.0.dev"

build:
    number: 3

source:
    git_url: https://github.com/m-labs/llvmlite
    git_tag: artiq-6.0

requirements:
    build:
        - python
        - llvm-or1k 6.0.0 25
        - setuptools
        - ncurses
    run:
        - python
        - ncurses

test:
    imports:
        - llvmlite_artiq
        - llvmlite_artiq.binding

about:
    home: https://pypi.python.org/pypi/llvmlite/
    license: BSD
